'use client';

/**
 * PaymentStatusPageContent — client section component.
 *
 * v1.7.0 Story 2.4: Cart, Checkout and Payment Status UX.
 *
 * Fetches live payment/order status from the backend via browser-level proxy
 * route so that:
 *   - Playwright E2E tests can intercept with page.route().
 *   - Status is always fresh (no ISR cache — parent route is force-dynamic).
 *   - Refresh CTA triggers a re-fetch, not a re-render.
 *
 * Idempotency contract (NFR8 / NFR9):
 *   - Load and Refresh call the STATUS-READ endpoint (/api/v1/orders/[id]).
 *   - Retry CTA calls the RETRY-PAYMENT mutation with a fresh attempt key.
 *   - NO mutation on page load / back-button / second tab.
 *   - No duplicate "Order confirmed" toast on refresh.
 *
 * Anti-pattern guards (Story 2.4 spec):
 *   - Unknown backend status → pending_psp_confirmation (never optimistic paid).
 *   - No voucher delivery copy here (Story 2.5 owns ConfirmationHandoff content).
 *   - `empty` state is NEVER shown; missing order → access_denied or unavailable.
 *
 * ARCH-007: Customer-facing storefront only.
 */

import React, { useCallback, useEffect, useState } from 'react';

import { useLocale, useTranslations } from 'next-intl';
import { useRouter } from 'next/navigation';

import { PaymentStatusPanel } from '@/components/cells/PaymentStatusPanel/PaymentStatusPanel';
import { StateCard } from '@/components/molecules/StateCard/StateCard';

type OrderStatusData = {
  id: string;
  // R7 review fix: upstream may return number or string; normalize to string at the proxy.
  display_id?: string | number | null;
  payment_status?: string | null;
  updated_at?: string | null;
};

type Props = {
  orderId: string;
};

/**
 * Generates a stable idempotency key per retry attempt.
 *
 * F19 review fix: dropped `Date.now()` so the SAME retry produces the SAME
 * key — backend Stripe-style dedup can recognise a retried network request
 * as the same logical attempt. Cross-page-reload uniqueness is guaranteed
 * by the page-scoped `sessionToken` argument (a per-page-mount UUID-ish
 * value generated by `crypto.randomUUID()` when available, falling back to
 * a short timestamp+random string).
 *
 * R1 review fix (second pass): NOT exposed in URL query string — the
 * checkout page has no consumer for the key and embedding it in the URL
 * leaks the orderId via the browser referrer header. The key is generated
 * for diagnostic / logging purposes; the real idempotency surface for
 * payment retries lives in Story 6.1 (durable-retry resilience hardening).
 * Until then, the key is logged client-side only.
 */
export function generateAttemptKey(
  orderId: string,
  attemptNumber: number,
  sessionToken: string,
): string {
  return `retry-${orderId}-${sessionToken}-attempt-${attemptNumber}`;
}

/** Stable per-page-load token for retry idempotency. */
export function generateSessionToken(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

export function PaymentStatusPageContent({ orderId }: Props) {
  const t = useTranslations();
  const locale = useLocale();
  const router = useRouter();

  const [order, setOrder] = useState<OrderStatusData | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [fetchError, setFetchError] = useState<'unavailable' | 'access_denied' | null>(null);
  const [retryAttempt, setRetryAttempt] = useState(0);
  // F19 review fix: stable per-page-load session token used as part of the
  // retry idempotency key so the SAME retry produces the SAME key across
  // network retries within one user attempt.
  const [sessionToken] = useState<string>(() => generateSessionToken());

  const fetchOrderStatus = useCallback(
    async (isRefresh = false) => {
      if (isRefresh) {
        setRefreshing(true);
      } else {
        setLoading(true);
      }
      setFetchError(null);

      try {
        // STATUS-READ endpoint — never a mutation endpoint.
        const res = await fetch(`/api/v1/orders/${orderId}`, {
          cache: 'no-store',
          headers: { 'x-request-type': 'status-read' },
        });

        if (!res.ok) {
          // F1 review fix: distinguish access_denied (401/403) from unavailable (5xx/404).
          // Per UX-state contract, payment-status MUST NOT show `empty` —
          // missing-order falls through to `unavailable` or `access_denied`.
          setFetchError(res.status === 401 || res.status === 403 ? 'access_denied' : 'unavailable');
          return;
        }

        const data = (await res.json()) as OrderStatusData;
        setOrder(data);
      } catch (error) {
        // R21 review fix: surface to client-side diagnostics. UI text stays
        // generic; the breadcrumb helps support recover the actual failure
        // without re-walking the customer through the steps.
        // eslint-disable-next-line no-console
        console.error('[payment-status] fetchOrderStatus failed', error);
        setFetchError('unavailable');
      } finally {
        setLoading(false);
        setRefreshing(false);
      }
    },
    [orderId],
  );

  useEffect(() => {
    void fetchOrderStatus(false);
    // Only run on mount — orderId is stable for the lifetime of this page.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ─── Handlers ─────────────────────────────────────────────────────────────

  const handleRefresh = useCallback(() => {
    void fetchOrderStatus(true);
  }, [fetchOrderStatus]);

  const handleContinue = useCallback(() => {
    // paid → handoff to confirmation surface (Story 2.5 owns the destination).
    // No duplicate "Order confirmed" toast — just navigate.
    router.push(`/${locale}/order/${orderId}/confirmed`);
  }, [locale, orderId, router]);

  const handleRetry = useCallback(() => {
    // Retry payment — explicit user-initiated mutation.
    //
    // R1 review fix (second pass): the previous implementation embedded
    // `attempt_key` and `order_id` as URL query params, but NO consumer in
    // `/checkout` reads those params. The idempotency-key surface is
    // therefore decorative until Story 6.1 lands the durable-retry path.
    // Until then, we generate the key for client-side diagnostics only and
    // navigate to `/checkout` without leaking `order_id` through the URL
    // (referrer headers, browser history, ad-pixel scripts).
    const newAttemptNumber = retryAttempt + 1;
    setRetryAttempt(newAttemptNumber);
    const idempotencyKey = generateAttemptKey(orderId, newAttemptNumber, sessionToken);
    // eslint-disable-next-line no-console
    console.info('[payment-status] retry initiated', {
      attempt: newAttemptNumber,
      // Key is logged for diagnostics; once Story 6.1 wires durable retry,
      // this key becomes the dedup signal for the payment-init endpoint.
      idempotencyKey,
    });

    router.push(`/${locale}/checkout`);
  }, [locale, orderId, retryAttempt, router, sessionToken]);

  const handleContactSupport = useCallback(() => {
    // Safe support handoff — pass the customer-visible `display_id` only
    // (NOT the internal Medusa order id). The display_id is already shown
    // on the panel; surfacing it via a query param so the help page can
    // pre-fill a contact form is consistent with what the customer can see.
    // R9 review fix (second pass): support handoff without context produces
    // friction; passing display_id keeps the support agent actionable.
    // Falls back to the bare `/pomoc` route when no display_id is known.
    const ref = order?.display_id ?? null;
    const target = ref ? `/${locale}/pomoc?order=${encodeURIComponent(String(ref))}` : `/${locale}/pomoc`;
    router.push(target);
  }, [locale, order, router]);

  const handleAbandon = useCallback(() => {
    // expired → abandon checkout / start over.
    router.push(`/${locale}/cart`);
  }, [locale, router]);

  // ─── Loading state ────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div
        role="status"
        aria-live="polite"
        aria-label={t('payment_status.loading')}
        className="flex items-center justify-center py-16"
        data-testid="payment-status-loading"
      >
        <span
          className="h-8 w-8 rounded-full border-4 border-t-transparent border-[var(--color-warning)] motion-safe:animate-spin"
          aria-hidden="true"
        />
        <span className="sr-only">{t('payment_status.loading')}</span>
      </div>
    );
  }

  // ─── Error / not found state ──────────────────────────────────────────────

  if (fetchError || !order) {
    // F1 review fix: route 401/403 to a distinct access_denied surface so the
    // UI never shows order data the customer is not authorised to see, and
    // never silently masks an authz failure as "unavailable".
    const isAccessDenied = fetchError === 'access_denied';
    return (
      <StateCard
        variant="unavailable"
        title={t(
          isAccessDenied
            ? 'payment_status.access_denied_title'
            : 'payment_status.unavailable_title',
        )}
        description={t(
          isAccessDenied
            ? 'payment_status.access_denied_body'
            : 'payment_status.unavailable_body',
        )}
        data-testid={
          isAccessDenied ? 'payment-status-access-denied' : 'payment-status-unavailable'
        }
        action={
          <button
            type="button"
            onClick={handleContactSupport}
            className="min-h-11 rounded-full bg-action px-6 py-3 text-base font-medium text-action-on-primary"
          >
            {t('payment_status.support_required.cta')}
          </button>
        }
      />
    );
  }

  // ─── Payment status panel ─────────────────────────────────────────────────

  return (
    <div className="mx-auto max-w-lg" data-testid="payment-status-content">
      <PaymentStatusPanel
        status={order.payment_status}
        lastUpdate={order.updated_at}
        orderId={
          order.display_id !== null && order.display_id !== undefined
            ? String(order.display_id)
            : order.id
        }
        onContinue={handleContinue}
        onRefresh={handleRefresh}
        onRetry={handleRetry}
        onContactSupport={handleContactSupport}
        onAbandon={handleAbandon}
        isLoading={refreshing}
      />
    </div>
  );
}
